### ISSUE TITLE
God of War III: Remastered (1.01) CUSA01623 crashes the game when cheats enabled.

### ISSUE THREAD

**Issue by sfhdfshdfh** [GoldHEN/GoldHEN_Cheat_Repository#198]
ps4 5.05 goldhen 2.3, game version 1.01 
tested the json cheat only(mc4 doesn't work/not recognized/not found)
(goldhen "showTitleId/gameVer" on the game icons says 1.01 but game properties says v1.00)
(also ps4 file explorer shows that there is no patch files in path '/user/patch/CUSA01623', its only the main fpkg that is ~37gb in size)

the cheats do not work, as soon as you enable any of them it crashes the game few seconds in (sometimes immediately).

i've also tried to install that 9mb 1.02 patch/update of the game but it throws an error and fails. couldn't find the 1.01 patch either, i think there is none, the game file itself is v1.01 i suppose.

**Comment by Contra49628** [comment]
Rename these files to version 01.00 using PS4Xplore. Do not change anything in the text of the files. Keep them in the 01.01 version.

CUSA01623_01.01.json
CUSA01623_01.01.mc4
CUSA01623_01.01.mc4.xml

If it still doesn't work, delete these mc4 files and try again. The modified json file should work.

Otherwise I do not understand. Goldhen 2.3 should already recognize the version of the merged pkg files. (my system version is 9.00)

**Comment by kmeps4** [comment]
Tested and no issues.
