### ISSUE TITLE
[Request] Add cheat

### ISSUE THREAD

**Issue by andercard0** [GoldHEN/GoldHEN_Cheat_Repository#64]
Hi, would be possible if exists, add cheats for the following game ? 

Game: Sniper Elite 5 
Game version: v01.06
Game ID: [CUSA16164] 

Thank you!

**Comment by chivu936** [comment]
CUSA18008 
V.1.11 
Resident Evil Village 
please.

**Comment by Contra49628** [comment]
For this game I would like to cheat:

Ace Combat 7
CUSA07202
v2.20
Max MRP

Pease...

**Comment by andercard0** [comment]
why don't you guys create your own request issue ?

**Comment by Contra49628** [comment]
I thought, since others have already posted here, this would be a good place for a collection page. The specific game is not named in the header.

By the way: game

There has been a cheat for the game you requested for a long time. Have you updated the cheats with the paths provided?

https://github.com/GoldHEN/GoldHEN_Cheat_Manager/releases/tag/v0.7.0

**Comment by Contra49628** [comment]
It is possible that the cheat does not appear because the game and the update were released in the same pkg file. In this case, version 1.00 will be displayed on the console. Simply rename the json cheat file to 01.00 using PS4 Explorer.

**Comment by bucanero** [comment]
We don't create cheats, read the following message about requests:

https://github.com/GoldHEN/GoldHEN_Cheat_Repository/discussions/42

**Comment by andercard0** [comment]
> We don't create cheats, read this message about requests: #42

Not a problem, thank you!
